# -*- coding: utf-8 -*-
"""proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cI8pWkIcEv4i1dYLgActmx74qGSkoS4Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

data=pd.read_csv('Estudio_Nacional_de_Caracterizacion.csv')

data.head()

data.info()

data.shape

data.describe(include=['O'])

"""Para ver las respuestas que hay en la pregunta:"""

col_sexo=[c for c in data.columns if c.strip().startswith('12.')][0]
print(col_sexo)
print(data[col_sexo].value_counts(dropna=False))

"""Para excluir la opción de Nan: dado que represta un vacio"""

opciones_validas_sexo = [
    '1. Femenino',
    '2. Masculino',
    '3. Prefiero no decir'
]

antes = len(data)
data = data[data[col_sexo].isin(opciones_validas_sexo)]
print(f"Filas antes: {antes} | Filas después: {len(data)} | Excluidas: {antes - len(data)}")

col_perdida=[c for c in data.columns if c.strip().startswith('15.')][0]

print(data[col_perdida].value_counts(dropna=False))

"""Aqui se normaliza la respuesta 2., 3. y 4. dado que repite la información"""

def limpiar_perdida(valor):
    if pd.isna(valor):
        return valor
    partes = [p.strip() for p in valor.split(',')]
    numeros = [p.split('.')[0].strip() for p in partes]
    if len(set(numeros)) == 1:
        return partes[0]  # duplicado real -> se queda con la unica opción
    else:
        return None  # inconsistencia número-etiqueta -> se descarta

data[col_perdida] = data[col_perdida].apply(limpiar_perdida)
print(data[col_perdida].value_counts(dropna=False))



"""Aqui se compara si respondio la pregunta 15. y cual fue su respuesta seleccionada frente a quien respondió la pregunta, esto para explicar el porque hay tantas respuestas sin un diagnóstico claro"""

col_ayuda = [c for c in data.columns if c.strip().startswith('3.')][0]
col_relacion = [c for c in data.columns if c.strip().startswith('4.')][0]

data['diagnostico_faltante'] = data[col_perdida].isna()
# queremos saber ¿La falta de diagnóstico claro se concentra en la relación del encuestador?
print(pd.crosstab(data[col_ayuda], data['diagnostico_faltante']))
print()
print(pd.crosstab(data[col_relacion], data['diagnostico_faltante']))

col_LSC=[c for c in data.columns if c.strip().startswith('38.')][0]

print(data[col_LSC].value_counts(dropna=False))

def limpiar_LSC(valor):
    if pd.isna(valor):
        return valor
    partes = [p.strip() for p in valor.split(',')]
    numeros = [p.split('.')[0].strip() for p in partes]
    if len(set(numeros)) == 1:
        return partes[0]  # duplicado real -> se queda con la unica opción
    else:
        return np.nan  # inconsistencia número-etiqueta -> se descarta

data[col_LSC] = data[col_LSC].apply(limpiar_LSC)
print(data[col_LSC].value_counts(dropna=False))

col_espanoloral=[c for c in data.columns if c.strip().startswith('39.')][0]

print(data[col_espanoloral].value_counts(dropna=False))

def limpiar_espanoloral(valor):
    if pd.isna(valor):
        return valor
    partes = [p.strip() for p in valor.split(',')]
    numeros = [p.split('.')[0].strip() for p in partes]
    if len(set(numeros)) == 1:
        return partes[0]  # duplicado real -> se queda con la unica opción
    else:
        return np.nan  # inconsistencia número-etiqueta -> se descarta

data[col_espanoloral] = data[col_espanoloral].apply(limpiar_espanoloral)
print(data[col_espanoloral].value_counts(dropna=False))

col_espanolescrito=[c for c in data.columns if c.strip().startswith('40.')][0]

print(data[col_espanolescrito].value_counts(dropna=False))

def limpiar_espanolescrito(valor):
    if pd.isna(valor):
        return valor
    partes = [p.strip() for p in valor.split(',')]
    numeros = [p.split('.')[0].strip() for p in partes]
    if len(set(numeros)) == 1:
        return partes[0]  # duplicado real -> se queda con la unica opción
    else:
        return np.nan  # inconsistencia número-etiqueta -> se descarta

data[col_espanolescrito] = data[col_espanolescrito].apply(limpiar_espanolescrito)
print(data[col_espanolescrito].value_counts(dropna=False))

"""Resumen del dataset ya depurado:"""

columnas_clave = {
    'Sexo': col_sexo,
    'Nivel de pérdida auditiva': col_perdida,
    'Desempeño en LSC': col_LSC,
    'Desempeño en español oral': col_espanoloral,
    'Desempeño en español escrito': col_espanolescrito,
}

resumen = []
for nombre, col in columnas_clave.items():
    total = len(data)
    faltantes = data[col].isna().sum()
    validos = total - faltantes
    moda = data[col].mode(dropna=True)
    moda = moda.iloc[0] if not moda.empty else None
    resumen.append({
        'Variable': nombre,
        'N total': total,
        'N válidos': validos,
        'N faltantes': faltantes,
        '% faltante': round(faltantes / total * 100, 1),
        'Categoría más frecuente': moda
    })

tabla_resumen = pd.DataFrame(resumen)
tabla_resumen

"""Aqui comienzan las medidas de tendencia central:"""

print("Moda de sexo:", data[col_sexo].mode(dropna=True).iloc[0])

def extraer_codigo(valor):
    if pd.isna(valor):
        return np.nan
    return int(valor.split('.')[0].strip())

variables = {
    'LSC': col_LSC,
    'Español oral': col_espanoloral,
    'Español escrito': col_espanolescrito,
}

resultados = []
for nombre, col in variables.items():
    codigos = data[col].apply(extraer_codigo)
    resultados.append({
        'Variable': nombre,
        'N válidos': codigos.notna().sum(),
        'Media': round(codigos.mean(), 2),
        'Varianza': round(codigos.var(), 2),
        'Desviación estándar': round(codigos.std(), 2),
        'Rango': codigos.max() - codigos.min(),
    })

tabla_stats = pd.DataFrame(resultados)
tabla_stats

orden = ['1. Alto', '2. Medio', '3. Bajo', '4. Nulo']

variables = {
    'LSC': col_LSC,
    'Español oral': col_espanoloral,
    'Español escrito': col_espanolescrito,
}

for nombre, col in variables.items():
    serie_ordenada = pd.Categorical(data[col], categories=orden, ordered=True)
    codigos_validos = serie_ordenada.codes[serie_ordenada.codes != -1]
    mediana = orden[int(np.median(codigos_validos))]
    moda = data[col].mode(dropna=True).iloc[0]
    print(f"{nombre}: Moda = {moda} | Mediana = {mediana}")

moda_perdida = data[col_perdida].mode(dropna=True).iloc[0]
print("Moda:", moda_perdida)

# 3. Para mediana, media, varianza, desviación estándar y rango:
#    "5. No sabe" se excluye de la escala numérica (no es un nivel de severidad,
#    es un dato no clasificable), igual que los NaN
def extraer_codigo_perdida(valor):
    if pd.isna(valor) or valor.strip().startswith('5.'):
        return np.nan
    return int(valor.split('.')[0].strip())

data['perdida_num'] = data[col_perdida].apply(extraer_codigo_perdida)

n_validos = data['perdida_num'].notna().sum()
mediana = data['perdida_num'].median()
media = data['perdida_num'].mean()
varianza = data['perdida_num'].var()
desviacion = data['perdida_num'].std()
rango = data['perdida_num'].max() - data['perdida_num'].min()

print(f"""
N válidos (excluye NaN y 'No sabe'): {n_validos}
Mediana: {mediana}  (1=Leve, 2=Moderada, 3=Severa, 4=Profunda)
Media: {round(media, 2)}
Varianza: {round(varianza, 2)}
Desviación estándar: {round(desviacion, 2)}
Rango: {rango}
""")

moda_perdida = data[col_perdida].mode(dropna=True).iloc[0]
print("Moda:", moda_perdida)

"""Aqui empiezan las gráficas"""

def graficar_barras(columna, orden, titulo, color='#4C72B0'):
    conteo = data[columna].value_counts(dropna=False)
    conteo = conteo.reindex(orden).fillna(0)

    plt.figure(figsize=(7,4))
    barras = plt.bar(conteo.index.astype(str), conteo.values, color=color)
    plt.title(titulo, fontsize=13)
    plt.ylabel('Número de personas')
    plt.xticks(rotation=30, ha='right')

    plt.ylim(0, conteo.values.max() * 1.15)

    for barra in barras:
        altura = barra.get_height()
        plt.text(barra.get_x() + barra.get_width()/2, altura + 6, int(altura),
                  ha='center', fontsize=8)

    plt.tight_layout()
    plt.show()

#graficas por pregunta
#sexo
graficar_barras(col_sexo, ['1. Femenino', '2. Masculino', '3. Prefiero no decir'],
                 'Distribución por sexo', color='#2e8b6f')
#nivel de perdida
orden_perdida = ['1. Hipoacúsia Leve', '2. Hipoacúsia Moderada',
                  '3. Hipoacúsia Severa', '4. Hipoacúsia Profunda', '5. No sabe', np.nan]
graficar_barras(col_perdida, orden_perdida, 'Nivel de pérdida auditiva',color='#cfcf55')

#desempeño
orden_desempeno = ['1. Alto', '2. Medio', '3. Bajo', '4. Nulo', np.nan]
graficar_barras(col_LSC, orden_desempeno, 'Desempeño comunicativo en LSC', color='#c9183c')
graficar_barras(col_espanoloral, orden_desempeno, 'Desempeño comunicativo en español oral', color='#c9183c')
graficar_barras(col_espanolescrito, orden_desempeno, 'Desempeño comunicativo en español escrito',color='#c9183c')

tabla_cruzada = pd.crosstab(data[col_perdida], data[col_LSC])
print(tabla_cruzada)

orden_perdida = ['1. Hipoacúsia Leve', '2. Hipoacúsia Moderada',
                  '3. Hipoacúsia Severa', '4. Hipoacúsia Profunda', '5. No sabe']
orden_desempeno = ['1. Alto', '2. Medio', '3. Bajo', '4. Nulo']

tabla_cruzada = pd.crosstab(data[col_perdida], data[col_LSC])
tabla_cruzada = tabla_cruzada.reindex(index=orden_perdida, columns=orden_desempeno)

tabla_cruzada.plot(kind='bar', figsize=(9,5), color=['#2E8B57','#6B8E23','#D4AC0D','#B03A2E'])
plt.title('Nivel de pérdida auditiva vs. desempeño comunicativo en LSC')
plt.xlabel('Nivel de pérdida auditiva')
plt.ylabel('Número de personas')
plt.xticks(rotation=30, ha='right')
plt.legend(title='Desempeño en LSC')
plt.tight_layout()
plt.show()

plt.figure(figsize=(7,5))
sns.heatmap(tabla_cruzada, annot=True, fmt='d', cmap='YlGn', cbar_kws={'label': 'N personas'})
plt.title('Nivel de pérdida auditiva vs. desempeño comunicativo en LSC')
plt.xlabel('Desempeño en LSC')
plt.ylabel('Nivel de pérdida auditiva')
plt.tight_layout()
plt.show()

"""Aqui se saca por diagrama de barras, sin embargo este no se usa en la presentación"""

orden_sexo = ['1. Femenino', '2. Masculino', '3. Prefiero no decir']
orden_perdida = ['1. Hipoacúsia Leve', '2. Hipoacúsia Moderada',
                  '3. Hipoacúsia Severa', '4. Hipoacúsia Profunda', '5. No sabe']

#tabla
tabla_sexo_perdida = pd.crosstab(data[col_sexo], data[col_perdida])
tabla_sexo_perdida = tabla_sexo_perdida.reindex(index=orden_sexo, columns=orden_perdida)
print(tabla_sexo_perdida)

tabla_sexo_perdida.plot(kind='bar', figsize=(9,5),
                         color=['#2E8B57','#6B8E23','#D4AC0D','#B03A2E','#c9183c'])
plt.title('Sexo vs. nivel de pérdida auditiva')
plt.xlabel('Sexo')
plt.ylabel('Número de personas')
plt.xticks(rotation=0)
plt.legend(title='Nivel de pérdida auditiva', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

Aqui se saca por proporción, lo cual lo hace mas interesante debido a que la cantidad de N es diferente en cada caso

orden_perdida = ['1. Hipoacúsia Leve', '2. Hipoacúsia Moderada',
                  '3. Hipoacúsia Severa', '4. Hipoacúsia Profunda', '5. No sabe']
orden_desempeno = ['1. Alto', '2. Medio', '3. Bajo', '4. Nulo']
colores = ['#2E8B57','#6B8E23','#D4AC0D','#c9183c']

def graficar_cruce_proporciones(col_x, orden_x, col_y, orden_y, titulo, xlabel, leyenda):
    tabla = pd.crosstab(data[col_x], data[col_y])
    tabla = tabla.reindex(index=orden_x, columns=orden_y)
    tabla_prop = tabla.div(tabla.sum(axis=1), axis=0)

    fig, ax = plt.subplots(figsize=(9,5))
    tabla_prop.plot(kind='bar', stacked=True, color=colores, ax=ax)

    for contenedor in ax.containers:
        etiquetas = [f'{valor*100:.1f}%' if valor > 0.02 else '' for valor in contenedor.datavalues]
        ax.bar_label(contenedor, labels=etiquetas, label_type='center', fontsize=8, color='white')

    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel('Proporción')
    plt.xticks(rotation=30, ha='right')
    plt.legend(title=leyenda, bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

    return tabla

# Pérdida auditiva vs. desempeño en LSC
tabla_perdida_lsc = graficar_cruce_proporciones(
    col_perdida, orden_perdida, col_LSC, orden_desempeno,
    'Nivel de pérdida auditiva vs. desempeño en LSC',
    'Nivel de pérdida auditiva', 'Desempeño en LSC'
)

colores = ['#2E8B57','#6B8E23','#D4AC0D','#B03A2E','#c9183c']

fig, ax = plt.subplots(figsize=(8,5))
tabla_prop.plot(kind='bar', stacked=True, color=colores, ax=ax)

# Agregar etiquetas de porcentaje dentro de cada segmento
for contenedor in ax.containers:
    etiquetas = [f'{valor*100:.1f}%' if valor > 0.02 else '' for valor in contenedor.datavalues]
    ax.bar_label(contenedor, labels=etiquetas, label_type='center', fontsize=8, color='white')

plt.title('Sexo vs. nivel de pérdida auditiva (proporción)')
plt.xlabel('Sexo')
plt.ylabel('Proporción')
plt.xticks(rotation=0)
plt.legend(title='Nivel de pérdida auditiva', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

from scipy.stats import chi2_contingency
chi2, p, dof, esperado = chi2_contingency(tabla_sexo_perdida.dropna(how='all').fillna(0))
print(f"Chi2 = {round(chi2,2)} | p-valor = {round(p,4)}")

orden_perdida = ['1. Hipoacúsia Leve', '2. Hipoacúsia Moderada',
                  '3. Hipoacúsia Severa', '4. Hipoacúsia Profunda', '5. No sabe']
orden_desempeno = ['1. Alto', '2. Medio', '3. Bajo', '4. Nulo']
colores = ['#2E8B57','#6B8E23','#D4AC0D','#c9183c']

def graficar_cruce_proporciones(col_x, orden_x, col_y, orden_y, titulo, xlabel, leyenda):
    tabla = pd.crosstab(data[col_x], data[col_y])
    tabla = tabla.reindex(index=orden_x, columns=orden_y)
    tabla_prop = tabla.div(tabla.sum(axis=1), axis=0)

    fig, ax = plt.subplots(figsize=(9,5))
    tabla_prop.plot(kind='bar', stacked=True, color=colores, ax=ax)

    for contenedor in ax.containers:
        etiquetas = [f'{valor*100:.1f}%' if valor > 0.02 else '' for valor in contenedor.datavalues]
        ax.bar_label(contenedor, labels=etiquetas, label_type='center', fontsize=8, color='white')

    plt.title(titulo)
    plt.xlabel(xlabel)
    plt.ylabel('Proporción')
    plt.xticks(rotation=30, ha='right')
    plt.legend(title=leyenda, bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

    return tabla

# 1. Pérdida auditiva vs. desempeño en español oral
tabla_perdida_oral = graficar_cruce_proporciones(
    col_perdida, orden_perdida, col_espanoloral, orden_desempeno,
    'Nivel de pérdida auditiva vs. desempeño en español oral',
    'Nivel de pérdida auditiva', 'Desempeño en español oral'
)

# 2. Pérdida auditiva vs. desempeño en español escrito
tabla_perdida_escrito = graficar_cruce_proporciones(
    col_perdida, orden_perdida, col_espanolescrito, orden_desempeno,
    'Nivel de pérdida auditiva vs. desempeño en español escrito',
    'Nivel de pérdida auditiva', 'Desempeño en español escrito'
)